container_image = docker://lsvaren/transformers

Universe = container
Executable = run_all_comparison_reg.sh
transfer_input_files = file:///staging/c/cdonahue6/birdsong/benchmark_data/3470165.tar.gz, CHURP,  file:///staging/c/cdonahue6/birdsong/tweety_bert.tar.gz,  file:///staging/c/cdonahue6/birdsong/CHURP_outputs_regular.tar.gz 

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_output_files = comparison_outputs_reg.tar.gz
output_destination = file:///staging/c/cdonahue6/birdsong/



+WantGPULab = true
+WantFlock = true
+GPUJobLength = "long"
Requirements = (Target.HasCHTCStaging == true)
gpus_minimum_memory = 130 GB
request_memory = 130 GB
request_disk = 200 GB
request_cpus = 2
request_gpus = 1



batch_name = comparison_all_reg
output = logs/$(batch_name).out
error = logs/$(batch_name).err
log = logs/$(batch_name).log
