container_image = docker://lsvaren/transformers

Universe = container
Executable = train_CHURP.sh
transfer_input_files = environment.yml

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_output_files = environment.tar.gz
output_destination = file:///staging/c/cdonahue6/birdsong/

Requirements = (Target.HasCHTCStaging == true)
request_memory = 30 GB
request_disk = 100 GB
request_cpus = 1

batch_name = make_env
output = logs/$(batch_name).out
error = logs/$(batch_name).err
log = logs/$(batch_name).log
queue
