container_image = docker://cdonahue6/churp:latest

Universe = container
Executable = run_all_comparison_reg.sh
transfer_input_files = src, scripts, file:///staging/c/cdonahue6/birdsong/files.tar.gz, file:///staging/c/cdonahue6/birdsong/models.tar.gz  file:///staging/c/cdonahue6/birdsong/tweety_bert.tar.gz

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_output_files = final_outputs.tar.gz
output_destination = file:///staging/c/cdonahue6/birdsong/


+WantGPULab = true
+WantFlock = true
+GPUJobLength = "long"
Requirements = (Target.HasCHTCStaging == true)
gpus_minimum_memory = 130 GB
request_memory = 130 GB
request_disk = 500 GB
request_cpus = 2
request_gpus = 1

batch_name = comparison_all_reg
output = logs/$(batch_name).out
error = logs/$(batch_name).err
log = logs/$(batch_name).log
