
container_image = docker://lsvaren/transformers

Universe = container
Executable = tweety_pretrain.sh
transfer_input_files = file:///staging/cdonahue6/birdsong/benchmark_data/3470165.tar.gz

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_output_files = tweety_bert.tar.gz
output_destination = file:///staging/cdonahue6/birdsong/

+WantGPULab = true
+WantFlock = true
+GPUJobLength = "long"
Requirements = (Target.HasCHTCStaging == true)
gpus_minimum_memory = 130 GB
request_memory = 130 GB
request_disk = 1056 GB
request_cpus = 5
request_gpus = 1

batch_name = tweetyBERT_pretraining
output = $(batch_name).out
error = $(batch_name).err
log = $(batch_name).log
queue 
