container_image = docker://lsvaren/transformers
universe = container
executable = run_comparison.sh

# Pass the parallel job index (0 through 9) to the script
arguments = $(Process)

transfer_input_files = file:///staging/cdonahue6/birdsong/benchmark_data/3470165.tar.gz,comparing.py,file:///staging/cdonahue6/birdsong/birdsong_segmentation_out_$(Process).tar.gz,file:///staging/cdonahue6/birdsong/tweety_bert2.tar.gz,plots.py

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# Dynamically name output package so jobs don't overwrite each other in staging
transfer_output_files = comparison_$(Process).tar.gz
output_destination = file:///staging/cdonahue6/birdsong/

requirements=(HasCHTCStaging == true)
request_memory = 20 GB
request_disk = 200 GB
request_cpus = 1

batch_name = birdsong_comparison
output = logs/$(batch_name)_$(Process).out
error = logs/$(batch_name)_$(Process).err
log = logs/$(batch_name)_$(Process).log

queue 11
