container_image = docker://lsvaren/transformers


Universe = container
Executable = run_segmentation.sh

arguments = $(Process)

transfer_input_files = cluster_and_seg.py,file:///staging/cdonahue6/birdsong/benchmark_data/3470165.tar.gz,file:///staging/cdonahue6/birdsong/birdsong_inference_out.tar.gz


requirements=(HasCHTCStaging == true)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_output_files = birdsong_segmentation_out_$(Process).tar.gz
output_destination = file:///staging/cdonahue6/birdsong/

request_memory = 20 GB
request_disk = 100 GB
request_cpus = 1

batch_name = birdsong_segmentation
output = logs/$(batch_name)_$(Process).out
error = logs/$(batch_name)_$(Process).err
log = logs/$(batch_name)_$(Process).log
queue 11 
