container_image = docker://lsvaren/transformers

Universe = container
Executable = run_model.sh
transfer_input_files = file:///staging/cdonahue6/birdsong/benchmark_data/3470165.tar.gz, model.py, train.py

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_output_files = birdsong_train.tar.gz
output_destination = file:///staging/cdonahue6/birdsong/

+WantGPULab = true
+WantFlock = true
+GPUJobLength = "long"
Requirements = (Target.HasCHTCStaging == true)
gpus_minimum_memory = 130 GB
request_memory = 130 GB
request_disk = 1056 GB
request_cpus = 5
request_gpus = 1

batch_name = birdsong_train
output = logs/$(batch_name).out
error = logs/$(batch_name).err
log = logs/$(batch_name).log
queue
